import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Montserrat, Space_Grotesk, DM_Serif_Display} from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/components/Providers";
import SocketAnnouncer from "@/components/SocketAnnouncer";
import { getUser } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const idGrotesk = localFont({
  src: [{ path: "../public/font/IDGrotesk-Regular.ttf", weight: "400" }],
  variable: "--font-id",
});

const benzGrotesk = localFont({
  src: [
    { path: "../public/font/Benz-Grotesk.ttf", weight: "400" },
  ],
  variable: "--font-benz",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-spacegrotesk",
  subsets: ["latin"],
})

// const dmSerif = localFont({
//   src: [
//     {
//       path: "../public/font/DMSerifDisplay-Regular.ttf",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "../public/font/DMSerifDisplay-Italic.ttf",
//       weight: "400",
//       style: "italic",
//     },
//   ],
//   variable: "--font-dmserif",
// });

const dmSerif = DM_Serif_Display({
  variable: "--font-dmserif",
  weight: ["400"],
  subsets: ["latin"],
  style: ["normal", "italic"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { user } = await getUser();

  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${geistSans.variable} ${spaceGrotesk.variable} ${geistMono.variable} ${montserrat.variable} ${idGrotesk.variable} ${benzGrotesk.variable} ${inter.variable} ${dmSerif.variable}`}>
        <SocketAnnouncer userId={user?.id} />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
